workflows:
  ios-build:
    name: iOS Build (No Signing)
    environment:
      xcode: latest
    scripts:
      - cd ios
      - swift package generate-xcodeproj
      - xcodebuild -project iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -configuration Debug build
    artifacts:
      - ios/build/Debug-iphonesimulator/*.app
